---
- name: Copy file to remote hosts
  hosts: planetexpress
  gather_facts: no

  tasks:
          - name: Copy from localhost to remote host
            copy:
                    src: ~/ans/files/fryresume.txt
                    dest: ~/fryresume.txt
          - name: removing file created
            file:
                    path: ~/fryresume.txt
                    state: absent
          - name: download a file to my remote servers
            get_url:
                    url: http://www.clamav.net/downloads/production/clamav-0.99.3.tar.gz
                    dest: ~/clamav-0.99.3.tar.gz
