---
- name: More looping
  hosts: localhost
  gather_facts: yes

  vars_files:
          - ~/ans/vars/yummysnacks.yml

  tasks:
          - name: Show off loop control
            debug:
                    var: item
            loop:
                    - server1
                    - server2
                    - server3
                    - server4
            loop_control:
                    pause: 3

          - name: loop across complex data
            debug:
                    msg: "{{ item.name }} belongs to the {{ item.groups }} group"
            loop: "{{ snacks }}"
